# This file is intended to be a file which specifically calls out modules to be published to the Astronomer
# Registry as well as top-level Provider metadata. The file should not be packaged and solely lives in the
# repo. The modules listed should pertain to latest, released version of the repo.

# Python package name.
package-name: mlflow_provider
# The name of the provider to be displayed on the Registry.
display-name: MLflow Provider
# A description to be displayed on the main Provider page.
description: An Mlflow provider for Apache Airflow for Machine Learning Ops.
# URL for where user should find the documentation for the Provider. This could be a link to the README,
# an external docs site, etc.
docs_url: https://github.com/astronomer/airflow-provider-mlflow/blob/main/README.md

# The next sections should be organized by module type (e.g. operators, hooks, functions, decorators, etc.).
#
# Within each section, the ``module`` value should be the path.to.the.module.specifically.
# For example, if the import path for a function is `from mlflow_provider.hooks.sample_hook import MLflowHook` then the
# value should be "mlflow_provider.hooks.sample_hook.MLflowHook".

hooks:
  - module: mlflow_provider.hooks.client.MLflowClientHook
  - module: mlflow_provider.hooks.deployment.MLflowDeploymentHook
  - module: mlflow_provider.hooks.pyfunc.MLflowPyfuncHook

operators:
  - module: mlflow_provider.operators.registry.CreateRegisteredModelOperator
  - module: mlflow_provider.operators.registry.GetRegisteredModelOperator
  - module: mlflow_provider.operators.registry.DeleteRegisteredModelOperator
  - module: mlflow_provider.operators.registry.GetLatestModelVersionsOperator
  - module: mlflow_provider.operators.registry.CreateModelVersionOperator
  - module: mlflow_provider.operators.registry.GetModelVersionOperator
  - module: mlflow_provider.operators.registry.DeleteModelVersionOperator
  - module: mlflow_provider.operators.registry.TransitionModelVersionStageOperator
  - module: mlflow_provider.operators.deployment.CreateDeploymentOperator
  - module: mlflow_provider.operators.deployment.PredictOperator
  - module: mlflow_provider.operators.pyfunc.AirflowPredictOperator

#sensors:
#  - module: mlflow_provider.sensors.sample_sensor.SampleSensor
