ARG IMAGE_NAME="quay.io/astronomer/ap-airflow:2.4.3"
FROM ${IMAGE_NAME}

USER root
COPY mlflow_provider ${AIRFLOW_HOME}/mlflow_provider
COPY setup.cfg ${AIRFLOW_HOME}/mlflow_provider/setup.cfg
COPY setup.py ${AIRFLOW_HOME}/mlflow_provider/setup.py

RUN pip install -e ${AIRFLOW_HOME}/mlflow_provider[dev]
USER astro
